# Generated by Django 4.0.3 on 2022-03-08 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_delete_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
