# Generated by Django 4.0.3 on 2022-03-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_alter_jobseeker_special_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='education_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='permanent_address',
            field=models.TextField(),
        ),
    ]
