# Generated by Django 4.0.3 on 2022-03-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0003_alter_jobseeker_education_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=1000)),
                ('education', models.TextField(max_length=1000)),
                ('skills', models.TextField(max_length=1000)),
                ('experience', models.TextField(max_length=1000)),
                ('about', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/imgaes'),
        ),
    ]
