# Generated by Django 4.0.3 on 2022-03-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0006_jobseeker_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='dob',
            field=models.DateField(),
        ),
    ]
