# Generated by Django 4.0.3 on 2022-03-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0008_resume_key_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='key_skill',
            new_name='certifications',
        ),
        migrations.AddField(
            model_name='resume',
            name='summary',
            field=models.CharField(default='', max_length=255),
        ),
    ]
