# Generated by Django 4.0.3 on 2022-03-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(default='', max_length=254, unique=True)),
                ('phone_number', models.IntegerField()),
                ('school_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('skills_hire_for', models.TextField()),
                ('exprience_inhiring', models.CharField(choices=[('0', 'Less Than 1 year'), ('1', '1+ Year'), ('2', '2+ Year'), ('3', '3+ Year'), ('4', '4+ Year'), ('5', '5+ Year'), ('6', '6+ Year'), ('7', '7+ Year'), ('8', '8+ Year'), ('9', '9+ Year'), ('10', '10+ Year')], max_length=255)),
                ('level', models.CharField(choices=[('junior level', 'Junior Level'), ('mid level', 'Mid Level '), ('high level', 'High Level')], max_length=255)),
            ],
        ),
    ]
