# Generated by Django 4.0.3 on 2022-03-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.TextField()),
                ('qualification', models.TextField()),
                ('experience', models.TextField()),
                ('jobtype', models.CharField(choices=[('full time', 'Full Time'), ('part time', 'Part Time')], max_length=255)),
                ('woking_time', models.CharField(max_length=200)),
                ('schedule', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
            ],
        ),
    ]
