# Generated by Django 4.0.3 on 2022-03-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_jobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
