# Generated by Django 4.0.3 on 2022-03-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_jobpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
