# Generated by Django 4.0.3 on 2022-03-19 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_jobpost_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='deadline',
            new_name='application_deadline',
        ),
    ]
