# Generated by Django 4.0.3 on 2022-03-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_rename_deadline_jobpost_application_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='title',
            new_name='job_title',
        ),
    ]
