# Generated by Django 4.0.3 on 2022-03-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_rename_title_jobpost_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='requirements',
            field=models.TextField(null=True),
        ),
    ]
