# Generated by Django 4.0.3 on 2022-03-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_alter_jobpost_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='scale_of_pay',
            field=models.CharField(default='', max_length=255),
        ),
    ]
